<a href="https://colab.research.google.com/github/sherlinvarshitha/STML-Ass/blob/main/STML_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1

In [ ]:
import pandas as pd
df=pd.read_csv('/content/train.csv')
df

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,2
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,2
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,794,1,0.5,1,0,1,2,0.8,106,6,...,1222,1890,668,13,4,19,1,1,0,0
1996,1965,1,2.6,1,0,0,39,0.2,187,4,...,915,1965,2032,11,10,16,1,1,1,2
1997,1911,0,0.9,1,1,1,36,0.7,108,8,...,868,1632,3057,9,1,5,1,1,0,3
1998,1512,0,0.9,0,4,1,46,0.1,145,5,...,336,670,869,18,10,19,1,1,1,0
1999,510,1,2.0,1,5,1,45,0.9,168,6,...,483,754,3919,19,4,2,1,1,1,3

In [ ]:
y=df['price_range']
y

0       1
1       2
2       2
3       2
4       1
       ..
1995    0
1996    2
1997    3
1998    0
1999    3
Name: price_range, Length: 2000, dtype: int64

In [ ]:
x=df.drop('price_range',axis=1)
x

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi
0,842,0,2.2,0,1,0,7,0.6,188,2,2,20,756,2549,9,7,19,0,0,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,6,905,1988,2631,17,3,7,1,1,0
2,563,1,0.5,1,2,1,41,0.9,145,5,6,1263,1716,2603,11,2,9,1,1,0
3,615,1,2.5,0,0,0,10,0.8,131,6,9,1216,1786,2769,16,8,11,1,0,0
4,1821,1,1.2,0,13,1,44,0.6,141,2,14,1208,1212,1411,8,2,15,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,794,1,0.5,1,0,1,2,0.8,106,6,14,1222,1890,668,13,4,19,1,1,0
1996,1965,1,2.6,1,0,0,39,0.2,187,4,3,915,1965,2032,11,10,16,1,1,1
1997,1911,0,0.9,1,1,1,36,0.7,108,8,3,868,1632,3057,9,1,5,1,1,0
1998,1512,0,0.9,0,4,1,46,0.1,145,5,5,336,670,869,18,10,19,1,1,1
1999,510,1,2.0,1,5,1,45,0.9,168,6,16,483,754,3919,19,4,2,1,1,1

In [ ]:
upd=x-x.min()/x.max()-x.min()
upd

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi
0,340.749249,0.0,1.533333,0.0,1.0,0.0,4.96875,0.4,107.6,0.875,2.0,20.0,255.74975,2292.935968,3.736842,7.0,16.9,0.0,0.0,1.0
1,519.749249,1.0,-0.166667,1.0,0.0,1.0,50.96875,0.5,55.6,1.875,6.0,905.0,1487.74975,2374.935968,11.736842,3.0,4.9,1.0,1.0,0.0
2,61.749249,1.0,-0.166667,1.0,2.0,1.0,38.96875,0.7,64.6,3.875,6.0,1263.0,1215.74975,2346.935968,5.736842,2.0,6.9,1.0,1.0,0.0
3,113.749249,1.0,1.833333,0.0,0.0,0.0,7.96875,0.6,50.6,4.875,9.0,1216.0,1285.74975,2512.935968,10.736842,8.0,8.9,1.0,0.0,0.0
4,1319.749249,1.0,0.533333,0.0,13.0,1.0,41.96875,0.4,60.6,0.875,14.0,1208.0,711.74975,1154.935968,2.736842,2.0,12.9,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,292.749249,1.0,-0.166667,1.0,0.0,1.0,-0.03125,0.6,25.6,4.875,14.0,1222.0,1389.74975,411.935968,7.736842,4.0,16.9,1.0,1.0,0.0
1996,1463.749249,1.0,1.933333,1.0,0.0,0.0,36.96875,0.0,106.6,2.875,3.0,915.0,1464.74975,1775.935968,5.736842,10.0,13.9,1.0,1.0,1.0
1997,1409.749249,0.0,0.233333,1.0,1.0,1.0,33.96875,0.5,27.6,6.875,3.0,868.0,1131.74975,2800.935968,3.736842,1.0,2.9,1.0,1.0,0.0
1998,1010.749249,0.0,0.233333,0.0,4.0,1.0,43.96875,-0.1,64.6,3.875,5.0,336.0,169.74975,612.935968,12.736842,10.0,16.9,1.0,1.0,1.0
1999,8.749249,1.0,1.333333,1.0,5.0,1.0,42.96875,0.7,87.6,4.875,16.0,483.0,253.74975,3662.935968,13.736842,4.0,-0.1,1.0,1.0,1.0

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(upd,y,test_size=0.7,random_state=30)
print(x_train)
print(x_test)
print(y_train)
print(y_test)

      battery_power  blue  clock_speed  dual_sim   fc  four_g  int_memory  \
1320    1036.749249   1.0     1.633333       0.0  6.0     1.0    10.96875
611     1456.749249   1.0     1.233333       1.0  0.0     0.0     1.96875
279      321.749249   1.0    -0.166667       0.0  0.0     0.0    36.96875
1932     216.749249   1.0     0.933333       1.0  1.0     1.0    27.96875
1432     128.749249   0.0     1.333333       0.0  9.0     1.0    11.96875
...             ...   ...          ...       ...  ...     ...         ...
500      776.749249   1.0    -0.166667       1.0  1.0     0.0    51.96875
1837     481.749249   0.0    -0.066667       1.0  0.0     1.0    42.96875
941      241.749249   0.0    -0.166667       1.0  0.0     1.0    30.96875
421      676.749249   0.0     1.533333       1.0  6.0     0.0    54.96875
1829     563.749249   0.0     1.033333       1.0  4.0     1.0    45.96875

      m_dep  mobile_wt  n_cores    pc  px_height    px_width          ram  \
1320    0.0       40.6    5.875   7.0      567.0   485.74975  1237.935968
611     0.0      109.6    0.875   3.0      304.0   136.74975  1152.935968
279     0.2      106.6    6.875   4.0      630.0   387.74975    37.935968
1932    0.2       12.6    1.875  12.0      662.0   496.74975  1344.935968
1432    0.3       99.6    6.875  13.0       66.0   947.74975   955.935968
...     ...        ...      ...   ...        ...         ...          ...
500    -0.1       23.6    6.875  16.0      581.0   249.74975   898.935968
1837   -0.1       49.6    2.875  11.0      948.0   704.74975  1795.935968
941     0.1       14.6    0.875   1.0     1587.0  1158.74975    59.935968
421     0.1        3.6    1.875  17.0       96.0   851.74975  2235.935968
1829    0.1       81.6    4.875   8.0     1188.0  1447.74975     8.935968

           sc_h  sc_w  talk_time  three_g  touch_screen  wifi
1320  12.736842  10.0        9.9      1.0           1.0   1.0
611   10.736842   5.0        0.9      0.0           0.0   0.0
279    7.736842   9.0        8.9      0.0           0.0   1.0
1932   4.736842   9.0        9.9      1.0           1.0   1.0
1432   6.736842   8.0        9.9      1.0           0.0   0.0
...         ...   ...        ...      ...           ...   ...
500    1.736842   1.0       17.9      0.0           0.0   1.0
1837  -0.263158   3.0        3.9      1.0           0.0   1.0
941   13.736842  10.0        1.9      1.0           0.0   0.0
421   10.736842  14.0        7.9      1.0           1.0   0.0
1829   2.736842   0.0        9.9      1.0           0.0   0.0

[600 rows x 20 columns]
      battery_power  blue  clock_speed  dual_sim    fc  four_g  int_memory  \
1856    1284.749249   0.0     1.933333       0.0   6.0     0.0    11.96875
364      414.749249   1.0     1.933333       0.0   0.0     0.0    33.96875
1948     246.749249   0.0     0.733333       0.0   0.0     0.0    22.96875
1458     866.749249   0.0    -0.166667       0.0  10.0     1.0    39.96875
609      710.749249   0.0     1.933333       0.0   1.0     1.0    43.96875
...             ...   ...          ...       ...   ...     ...         ...
304      675.749249   0.0     0.233333       0.0   1.0     1.0    26.96875
193     1021.749249   1.0     1.733333       0.0   5.0     1.0    54.96875
1193     628.749249   0.0     1.133333       1.0   0.0     0.0    24.96875
505     1344.749249   1.0    -0.066667       0.0   1.0     0.0    16.96875
1275    1231.749249   1.0     0.833333       1.0   4.0     1.0     3.96875

      m_dep  mobile_wt  n_cores    pc  px_height    px_width          ram  \
1856    0.8       34.6    2.875  15.0      616.0   411.74975  2781.935968
364     0.1      114.6    2.875  12.0      188.0   491.74975  1213.935968
1948    0.8       29.6    5.875  14.0       88.0   208.74975  1717.935968
1458    0.0       10.6   -0.125  20.0      907.0   424.74975  1333.935968
609     0.1       21.6    2.875   8.0      611.0  1214.74975  1992.935968
...     ...        ...      ...   ...        ...         ...          ...
304     0.2      110.6    0.875   8.0      178.0   381.74975    54.935968
193     0.0       36.6    0.875   6.0      247.0    38.74975  3714.935968
1193    0.7       20.6   -0.125   8.0     1495.0  1078.74975    58.935968
505     0.5       78.6   -0.125   2.0       83.0   272.74975  1076.935968
1275    0.7       89.6   -0.125  15.0      590.0   496.74975  3231.935968

           sc_h  sc_w  talk_time  three_g  touch_screen  wifi
1856  12.736842   0.0       11.9      1.0           0.0   0.0
364    7.736842   0.0       11.9      0.0           1.0   0.0
1948  11.736842   5.0       10.9      0.0           1.0   1.0
1458   6.736842   0.0       11.9      1.0           0.0   0.0
609    8.736842   3.0        1.9      1.0           1.0   1.0
...         ...   ...        ...      ...           ...   ...
304   12.736842   5.0       16.9      1.0           0.0   0.0
193   12.736842  12.0        7.9      1.0           1.0   1.0
1193   8.736842   5.0        8.9      1.0           1.0   0.0
505    9.736842   6.0        8.9      0.0           1.0   1.0
1275   0.736842   4.0        7.9      1.0           1.0   1.0

[1400 rows x 20 columns]
1320    1
611     1
279     0
1932    1
1432    0
       ..
500     0
1837    1
941     0
421     2
1829    0
Name: price_range, Length: 600, dtype: int64
1856    3
364     0
1948    1
1458    1
609     2
       ..
304     0
193     3
1193    0
505     1
1275    3
Name: price_range, Length: 1400, dtype: int64

Q2

In [ ]:
import pandas as pd
d=pd.read_csv('/content/sample_data/california_housing_train.csv')
d

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [ ]:
d.dtypes

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
dtype: object

In [ ]:
d.shape[0]

17000

In [ ]:
x=d.drop('median_house_value',axis=1)
y=d['median_house_value']
print(x)
print(y)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0
1        -114.47     34.40                19.0       7650.0          1901.0
2        -114.56     33.69                17.0        720.0           174.0
3        -114.57     33.64                14.0       1501.0           337.0
4        -114.57     33.57                20.0       1454.0           326.0
...          ...       ...                 ...          ...             ...
16995    -124.26     40.58                52.0       2217.0           394.0
16996    -124.27     40.69                36.0       2349.0           528.0
16997    -124.30     41.84                17.0       2677.0           531.0
16998    -124.30     41.80                19.0       2672.0           552.0
16999    -124.35     40.54                52.0       1820.0           300.0

       population  households  median_income
0          1015.0       472.0         1.4936
1          1129.0       463.0         1.8200
2           333.0       117.0         1.6509
3           515.0       226.0         3.1917
4           624.0       262.0         1.9250
...           ...         ...            ...
16995       907.0       369.0         2.3571
16996      1194.0       465.0         2.5179
16997      1244.0       456.0         3.0313
16998      1298.0       478.0         1.9797
16999       806.0       270.0         3.0147

[17000 rows x 8 columns]
0         66900.0
1         80100.0
2         85700.0
3         73400.0
4         65500.0
           ...
16995    111400.0
16996     79000.0
16997    103600.0
16998     85800.0
16999     94600.0
Name: median_house_value, Length: 17000, dtype: float64

In [ ]:
d.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

In [ ]:
upd=x-x.min()/x.max()-x.min()
upd

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
0,8.952169,0.874315,13.980769,5609.999947,1281.999845,1011.999916,470.999836,0.960374
1,8.792169,1.084315,17.980769,7647.999947,1899.999845,1125.999916,461.999836,1.286774
2,8.702169,0.374315,15.980769,717.999947,172.999845,329.999916,115.999836,1.117674
3,8.692169,0.324315,12.980769,1498.999947,335.999845,511.999916,224.999836,2.658474
4,8.692169,0.254315,18.980769,1451.999947,324.999845,620.999916,260.999836,1.391774
...,...,...,...,...,...,...,...,...
16995,-0.997831,7.264315,50.980769,2214.999947,392.999845,903.999916,367.999836,1.823874
16996,-1.007831,7.374315,34.980769,2346.999947,526.999845,1190.999916,463.999836,1.984674
16997,-1.037831,8.524315,15.980769,2674.999947,529.999845,1240.999916,454.999836,2.498074
16998,-1.037831,8.484315,17.980769,2669.999947,550.999845,1294.999916,476.999836,1.446474
16999,-1.087831,7.224315,50.980769,1817.999947,298.999845,802.999916,268.999836,2.481474

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(upd,y,test_size=0.2,random_state=30)
print(x_train)
print(x_test)
print(y_train)
print(y_test)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
7303    4.922169  0.674315           46.980769  2006.999947      333.999845
12831   1.452169  3.914315           17.980769  2632.999947      425.999845
13976   1.222169  4.354315           27.980769  1691.999947      249.999845
3268    5.402169  0.414315           28.980769  2648.999947      570.999845
7206    4.932169  0.684315           45.980769   822.999947      185.999845
...          ...       ...                 ...          ...             ...
500     6.272169 -0.485685           18.980769  6693.999947     1324.999845
12077   1.832169  5.864315           34.980769  1121.999947      182.999845
15277   0.982169  4.564315           50.980769  1169.999947      213.999845
4517    5.222169  0.444315           14.980769  2067.999947      261.999845
5925    5.052169  0.784315           45.980769  5074.999947     1269.999845

        population   households  median_income
7303    915.999916   295.999836       4.279274
12831  1493.999916   408.999836       5.784574
13976   686.999916   240.999836       5.516874
3268   3245.999916   550.999836       3.186974
7206    412.999916   171.999836       1.800074
...            ...          ...            ...
500    3683.999916  1289.999836       2.664674
12077   500.999916   169.999836       1.633474
15277   485.999916   216.999836       3.383474
4517    874.999916   295.999836       6.554674
5925   3344.999916  1104.999836       2.504474

[13600 rows x 8 columns]
       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
10914   2.412169  4.194315            3.980769  2896.999947      743.999845
6241    5.012169  0.914315           35.980769  1951.999947      366.999845
5904    5.062169  0.474315           45.980769  2546.999947      624.999845
9578    3.912169  3.204315           37.980769  3024.999947      606.999845
9444    4.012169  0.984315           32.980769  1186.999947      218.999845
...          ...       ...                 ...          ...             ...
12228   1.792169  5.234315           50.980769  1381.999947      293.999845
6639    4.982169  0.594315           39.980769   617.999947      131.999845
7850    4.862169  1.384315            8.980769  4119.999947      812.999845
4886    5.162169  0.694315           40.980769  1433.999947      296.999845
3618    5.352169  0.294315           25.980769  1794.999947      341.999845

        population  households  median_income
10914  1589.999916  631.999836       1.695974
6241    963.999916  368.999836       4.552974
5904   1384.999916  604.999836       2.480274
9578   2195.999916  590.999836       2.111274
9444    441.999916  201.999836       4.349174
...            ...         ...            ...
12228   557.999916  242.999836       1.490974
6639    638.999916  160.999836       2.121374
7850   2160.999916  708.999836       3.760874
4886   1001.999916  296.999836       2.896474
3618    431.999916  201.999836       5.386374

[3400 rows x 8 columns]
7303     170500.0
12831    248000.0
13976    254200.0
3268     182100.0
7206     133300.0
           ...
500      154600.0
12077     93800.0
15277    235600.0
4517     338800.0
5925     186800.0
Name: median_house_value, Length: 13600, dtype: float64
10914    127500.0
6241     261300.0
5904     192700.0
9578      62000.0
9444     396400.0
           ...
12228     94600.0
6639     159600.0
7850     151600.0
4886     195800.0
3618     500001.0
Name: median_house_value, Length: 3400, dtype: float64